### ISSUE TITLE
Support for multiple domain names

### ISSUE THREAD

**Issue by danielbayerlein** [pfulop/serverless-cloudfront-distribution-certificate#1]
Currently only one domain is supported. Support for multiple domain names would be great.

```yaml
domainNames:
  - "best.example.com"
  - "best.prod.example.com"
```

**Comment by pfulop** [comment]
Will look into it upcoming weekend

**Comment by pfulop** [comment]
It seems to me that there can be only one [ViewerCertificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html). This means I can create multiple certificates but I would be unable to use their ARN with only one CloudFront distribution. However, if I understand correctly you can create one certificate for the wildcard domain and then use multiple domains trough [Aliases](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-aliases)

**Comment by danielbayerlein** [comment]
You can create the certificate with [alternative names (SubjectAlternativeNames)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html).

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#requestCertificate-property


```yaml
domainName: "best.example.com"
subjectAlternativeNames:
  - "best.prod.example.com"
```

**Comment by danielbayerlein** [comment]
Thank you 👏
