### ISSUE TITLE
Add option to disable the plugin

### ISSUE THREAD

**Issue by mathan94** [pfulop/serverless-cloudfront-distribution-certificate#11]
It would be nice to have an attribute under the plugin to disable it on certain stages.

**Comment by pfulop** [comment]
Sure, any specific format of the attribute? Maybe you can try and submit a PR for this feature.

**Comment by mathan94** [comment]
I was thinking something like 'enabled' similar to what [serverless-domain-manager](https://github.com/amplify-education/serverless-domain-manager) uses

**Comment by mathan94** [comment]
Any chance of it being merged and released today if I raise the PR as we need this as an emergency?

**Comment by pfulop** [comment]
If there won't be any issues then sure.

**Comment by mathan94** [comment]
Hi I've made a PR. Can't push. Do you need to add me as a contributor?

**Comment by pfulop** [comment]
That shouldn't be necessary you should be able to create a fork to make your changes there and create PR with your fork as a source.

**Comment by mathan94** [comment]
I've just raised a PR. I've tested it locally and it works :) Please review it. Thank you

**Comment by pfulop** [comment]
I will fix vulnerabilities and publish it to npm.

**Comment by mathan94** [comment]
Thank you so much! Waiting for it :D

**Comment by pfulop** [comment]
Published in version 0.0.8. I also updated Readme to reflect the changes.


@mathan94  thank you for your contribution. 👍

**Comment by mathan94** [comment]
Thanks for getting this in so quickly! Can't thank you enough!

**Comment by mathan94** [comment]
@pfulop How long does it take for the publish. Can't pull 0.0.8 :(

**Comment by pfulop** [comment]
@mathan94 it takes some time to propagate, I am unfortunately in no control of this.
